### ISSUE TITLE
MlkitOcr.detectFromUri is null

### ISSUE THREAD

**Issue by albertytau** [agoldis/react-native-mlkit-ocr#33]
HI there, 

We try to use running expo sdk 45 and rn 0.69

import MlkitOcr, { MlkitOcrResult } from 'react-native-mlkit-ocr';

const sample_image = "data:image/jpeg;base64,/9j/4QF ............."
const text = await MlkitOcr.detectFromUri(sample_image);

we catch the error is MlkitOcr.detectFromUri is null

It seems  MlkitOcr is not well defined in the package react-native-mlkit-ocr

Kindly point out the mistakes we have made, many thanks

Albert

**Comment by nicramu** [comment]
bump, same issue

i call it like:

```
 let response = await ImagePicker.launchImageLibraryAsync(
    {
      mediaType: 'photo',
    });
await MlkitOcr.detectFromUri(response.uri);
```

and error is:
```
[Unhandled promise rejection: TypeError: null is not an object (evaluating 'MlkitOcr.detectFromUri')]
at node_modules/react-native-mlkit-ocr/src/index.tsx:68:30 in <global>
at node_modules/react-native-mlkit-ocr/src/index.tsx:69:15 in <global>
```

and response is like (so it does catches something):
```
Object {
  "assetId": null,
  "base64": null,
  "cancelled": false,
  "exif": null,
  "height": 1920,
  "type": "image",
  "uri": "file:///data/user/0/host.exp.exponent/cache/ImagePicker/79f43782-0251-4131-802a-994d714d1a81.png",
  "width": 1080,
}
```

**Comment by zirho** [comment]
just installed on my project I don't get this error 
However, I get type error.

I've tried, reinstalling and restarting ts server and restarting vs code. none of them worked.

```
Could not find a declaration file for module 'react-native-mlkit-ocr'. '/Users/yj/projects/aquadesk/AwesomeTSProject/node_modules/react-native-mlkit-ocr/lib/commonjs/index.js' implicitly has an 'any' type.
[Contribute a translation for #7016](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)
```

![image](https://user-images.githubusercontent.com/1251296/201525568-458f3f6e-d0cf-4bc8-8e21-c94c911d9d08.png)

**Comment by zirho** [comment]
https://github.com/agoldis/react-native-mlkit-ocr/pull/39 
this could possibly related.

**Comment by its-wufu** [comment]
I have both problems as well. 
`Cannot read property 'detectFromFile' of null`
and type declaration. Any news?

**Comment by blackirishmec** [comment]
Bump on this - same error. I'm in a .js vs .ts Expo managed project. Any help getting up and running?

**Comment by mikef80** [comment]
I was getting this error on Expo Go.  Switched to development build and it appears to be working now.
